### ISSUE TITLE
iOS 15 upgrade

### ISSUE THREAD

**Issue by Pankaj03** [chat-sdk/chat-sdk-ios#501]
1. **Is the bug present in the demo Chat SDK project?**
Demoproject is no more available.

2. **What modifications have you made to the Chat SDK?**
Just upgrade the SDK to support iOS 15.5 and Xcode 13.3.1

3. **iOS Version? Device or simulator?**
iOS 15.5 iPhoneX

4. **Steps taken to reproduce the problem:**
Compilation error on below:
self.navigationController?.pushViewController((BChatSDK.ui().appTabBarViewController())!, animated: false)

5. **Expected result:**
Should pass the compilation

6. **Actual result:**
Compilation error:
Value of type 'PInterfaceAdapter' has no member 'appTabBarViewController'

7. **Comments:**
-Not able to execute the code on Xcode 13.3.
- The code is working fine with Xcode 12.5
<img width="1465" alt="Screenshot 2022-07-04 at 12 45 52 PM" src="https://user-images.githubusercontent.com/4309635/177101750-30ddae1a-7770-45a3-90f2-3719d01a8c7d.png">
1

@bensmiley  Please help me on that issue.

Thanks in Advance!
